# Generated by Django 5.0.2 on 2025-06-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='certification_level',
            field=models.CharField(choices=[('DIVEMASTER', 'Divemaster'), ('INSTRUCTOR', 'Instructor'), ('SENIOR_INSTRUCTOR', 'Senior Instructor'), ('MASTER_INSTRUCTOR', 'Master Instructor'), ('COURSE_DIRECTOR', 'Course Director'), ('SKIPPER', 'Marinero'), ('CAPTAIN', 'Patrón'), ('OFFICE', 'Oficinista')], default='DIVEMASTER', max_length=50),
        ),
    ]
