# Generated by Django 5.0.2 on 2025-05-28 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diveschedule',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='diveschedule',
            name='customers',
        ),
        migrations.CreateModel(
            name='CustomerDiveActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to='users.diveactivity')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dive_activities', to='users.customer')),
                ('dive_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_activities', to='users.diveschedule')),
            ],
            options={
                'unique_together': {('customer', 'dive_schedule')},
            },
        ),
    ]
