# Generated by Django 5.0.2 on 2025-05-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdiveactivity',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ON_BOARD', 'On Board'), ('BACK_ON_BOAT', 'Back on Boat'), ('DEPARTED', 'Departed'), ('FINISHED', 'Finished')], default='PENDING', max_length=20),
        ),
    ]
