# Generated by Django 5.0.2 on 2025-05-28 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_diveschedule_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diveschedule',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.diveactivity'),
        ),
        migrations.AlterField(
            model_name='diveschedule',
            name='max_participants',
            field=models.IntegerField(default=46),
        ),
    ]
