# Generated by Django 5.0.2 on 2025-05-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customerdiveactivity_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diveschedule',
            name='activity',
        ),
    ]
