# Generated by Django 5.0.2 on 2025-05-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_diveschedule_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdiveactivity',
            name='needs_bcd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerdiveactivity',
            name='needs_guide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerdiveactivity',
            name='needs_insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerdiveactivity',
            name='needs_regulator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerdiveactivity',
            name='needs_wetsuit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerdiveactivity',
            name='tank_size',
            field=models.CharField(choices=[('10L', '10 Liters'), ('12L', '12 Liters'), ('15L', '15 Liters'), ('18L', '18 Liters')], default='12L', max_length=10),
        ),
    ]
