# Generated by Django 5.0.2 on 2025-05-29 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customerdiveactivity_needs_bcd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('DE', 'German'), ('IT', 'Italian'), ('PT', 'Portuguese'), ('RU', 'Russian'), ('ZH', 'Chinese'), ('JA', 'Japanese'), ('OTHER', 'Other')], default='EN', max_length=10),
        ),
        migrations.AddField(
            model_name='customerdiveactivity',
            name='has_arrived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerdiveactivity',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerdiveactivity',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DEPARTED', 'Departed'), ('FINISHED', 'Finished')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='diveschedule',
            name='special_notes',
            field=models.TextField(blank=True, help_text='Special requirements or important notes for this dive'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='certification_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('OPEN_WATER', 'Open Water'), ('ADVANCED_OPEN_WATER', 'Advanced Open Water'), ('RESCUE_DIVER', 'Rescue Diver'), ('DIVEMASTER', 'Divemaster'), ('INSTRUCTOR', 'Instructor')], default='BEGINNER', max_length=50),
        ),
    ]
