# Generated by Django 5.0.2 on 2025-05-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customer_default_tank_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdiveactivity',
            name='tank_size',
            field=models.CharField(choices=[('10L', '10 Liters'), ('12L', '12 Liters'), ('15L', '15 Liters'), ('EAN12L', 'NITROX 12 Liters'), ('EAN15L', 'NITROX 15 Liters')], default='12L', max_length=10),
        ),
    ]
