# Generated by Django 5.0.2 on 2025-06-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customerdiveactivity_tank_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='diving_insurance',
            field=models.FileField(blank=True, null=True, upload_to='customer_documents/insurance/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='diving_licence',
            field=models.FileField(blank=True, null=True, upload_to='customer_documents/licences/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='medical_check',
            field=models.FileField(blank=True, null=True, upload_to='customer_documents/medical/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='customer_profiles/'),
        ),
    ]
