# Generated by Django 5.0.2 on 2025-05-29 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customer_birthday_customer_country_customer_language_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='foot_size',
            field=models.FloatField(blank=True, help_text='Foot size (EU)', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in cm', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kg', null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='certification_level',
            field=models.CharField(choices=[('NONE', 'No certification'), ('BEGINNER', 'Beginner'), ('OPEN_WATER', 'Open Water'), ('ADVANCED_OPEN_WATER', 'Advanced Open Water'), ('RESCUE_DIVER', 'Rescue Diver'), ('DIVEMASTER', 'Divemaster'), ('INSTRUCTOR', 'Instructor')], default='NONE', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('FR', 'France'), ('DE', 'Germany'), ('IT', 'Italy'), ('ES', 'Spain'), ('PT', 'Portugal'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('CH', 'Switzerland'), ('AT', 'Austria'), ('SE', 'Sweden'), ('NO', 'Norway'), ('DK', 'Denmark'), ('FI', 'Finland'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('JP', 'Japan'), ('KR', 'South Korea'), ('CN', 'China'), ('IN', 'India'), ('BR', 'Brazil'), ('AR', 'Argentina'), ('MX', 'Mexico'), ('RU', 'Russia'), ('ZA', 'South Africa'), ('EG', 'Egypt'), ('TH', 'Thailand'), ('ID', 'Indonesia'), ('MY', 'Malaysia'), ('SG', 'Singapore'), ('PH', 'Philippines'), ('VN', 'Vietnam'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
        migrations.CreateModel(
            name='DivingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('FR', 'France'), ('DE', 'Germany'), ('IT', 'Italy'), ('ES', 'Spain'), ('PT', 'Portugal'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('CH', 'Switzerland'), ('AT', 'Austria'), ('SE', 'Sweden'), ('NO', 'Norway'), ('DK', 'Denmark'), ('FI', 'Finland'), ('AU', 'Australia'), ('NZ', 'New Zealand'), ('JP', 'Japan'), ('KR', 'South Korea'), ('CN', 'China'), ('IN', 'India'), ('BR', 'Brazil'), ('AR', 'Argentina'), ('MX', 'Mexico'), ('RU', 'Russia'), ('ZA', 'South Africa'), ('EG', 'Egypt'), ('TH', 'Thailand'), ('ID', 'Indonesia'), ('MY', 'Malaysia'), ('SG', 'Singapore'), ('PH', 'Philippines'), ('VN', 'Vietnam'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
                ('contact_person', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('departure_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diving_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diving_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DivingSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('depth_min', models.FloatField(help_text='Minimum depth in meters')),
                ('depth_max', models.FloatField(help_text='Maximum depth in meters')),
                ('difficulty_level', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('special_requirements', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diving_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diving_sites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('WETSUIT', 'Wetsuit'), ('BCD', 'BCD'), ('REGULATOR', 'Regulator'), ('FINS', 'Fins'), ('MASK', 'Mask'), ('BOOTS', 'Boots'), ('TANK', 'Tank'), ('WEIGHT', 'Weight'), ('OTHER', 'Other')], max_length=20)),
                ('size', models.CharField(choices=[('XS', 'Extra Small'), ('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra Large'), ('XXL', 'Extra Extra Large'), ('N/A', 'Not Applicable')], default='N/A', max_length=10)),
                ('quantity_total', models.IntegerField(default=1)),
                ('quantity_available', models.IntegerField(default=1)),
                ('condition', models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('OUT_OF_SERVICE', 'Out of Service')], default='GOOD', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diving_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DivingGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='users.customer')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.divinggroup')),
            ],
            options={
                'unique_together': {('group', 'customer')},
            },
        ),
    ]
