# Generated by Django 5.0.2 on 2025-06-02 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customer_diving_insurance_customer_diving_licence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('FR', 'France'), ('DE', 'Germany'), ('IT', 'Italy'), ('ES', 'Spain'), ('PT', 'Portugal'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('CH', 'Switzerland'), ('AT', 'Austria'), ('SE', 'Sweden'), ('NO', 'Norway'), ('DK', 'Denmark'), ('FI', 'Finland'), ('IN', 'India'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('CAT', 'Catalan'), ('OTHER', 'Other')], default='EN', max_length=10),
        ),
        migrations.AlterField(
            model_name='divinggroup',
            name='country',
            field=models.CharField(choices=[('US', 'United States'), ('CA', 'Canada'), ('GB', 'United Kingdom'), ('FR', 'France'), ('DE', 'Germany'), ('IT', 'Italy'), ('ES', 'Spain'), ('PT', 'Portugal'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('CH', 'Switzerland'), ('AT', 'Austria'), ('SE', 'Sweden'), ('NO', 'Norway'), ('DK', 'Denmark'), ('FI', 'Finland'), ('IN', 'India'), ('OTHER', 'Other')], default='OTHER', max_length=10),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('certification_level', models.CharField(choices=[('DIVEMASTER', 'Divemaster'), ('INSTRUCTOR', 'Instructor'), ('SENIOR_INSTRUCTOR', 'Senior Instructor'), ('MASTER_INSTRUCTOR', 'Master Instructor'), ('COURSE_DIRECTOR', 'Course Director')], default='DIVEMASTER', max_length=50)),
                ('certification_number', models.CharField(blank=True, max_length=100)),
                ('languages', models.CharField(help_text='Languages spoken (comma separated)', max_length=200)),
                ('experience_years', models.IntegerField(default=0, help_text='Years of diving experience')),
                ('specialties', models.TextField(blank=True, help_text='Specialties and additional certifications')),
                ('hire_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ON_LEAVE', 'On Leave')], default='ACTIVE', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Hourly rate in local currency', max_digits=8)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='staff_profiles/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diving_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customerdiveactivity',
            name='assigned_staff',
            field=models.ForeignKey(blank=True, help_text='Instructor/guide assigned to this activity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_activities', to='users.staff'),
        ),
    ]
