
# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_just_one_dive_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='just_one_dive',
            field=models.BooleanField(default=False, help_text='Check if this course/activity is for a single dive only'),
        ),
    ]
