# Generated by Django 5.0.2 on 2025-05-29 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customer_foot_size_customer_height_customer_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diveschedule',
            name='dive_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_dives', to='users.divingsite'),
        ),
    ]
