# Generated by Django 5.2.1 on 2025-06-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_just_one_dive_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('OPEN_WATER', 'Open Water Diver'), ('ADVANCED_OPEN_WATER', 'Advanced Open Water'), ('RESCUE_DIVER', 'Rescue Diver'), ('DIVEMASTER', 'Divemaster'), ('NITROX', 'Nitrox Specialty'), ('DEEP', 'Deep Diver Specialty'), ('WRECK', 'Wreck Diver Specialty'), ('NIGHT', 'Night Diver Specialty'), ('NAVIGATION', 'Underwater Navigation'), ('PHOTOGRAPHY', 'Underwater Photography'), ('SINGLE_DIVE', 'Inmersión Simple'), ('DOUBLE_DIVE', 'Inmersión Doble'), ('TRY_DIVE', 'Bautizo'), ('SCUBA_DIVER', 'Scuba Diver'), ('DIVING_LESSON', 'Clase de Buceo'), ('REFRESH', 'Refresh'), ('CUSTOM', 'Custom Course')], default='CUSTOM', max_length=30),
        ),
    ]
