# Generated by Django 5.2.1 on 2025-06-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='includes_instructor',
            field=models.BooleanField(default=True, help_text='Instructor is included in the course price'),
        ),
        migrations.AddField(
            model_name='course',
            name='includes_insurance',
            field=models.BooleanField(default=True, help_text='Insurance is included in the course price'),
        ),
        migrations.AddField(
            model_name='course',
            name='includes_material',
            field=models.BooleanField(default=True, help_text='Material is included in the course price'),
        ),
    ]
