# Generated by Django 5.2.1 on 2025-06-02 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_update_course_session_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesession',
            name='skills_covered',
            field=models.TextField(blank=True, help_text='Skills to be practiced in this lesson'),
        ),
    ]
