# Generated by Django 5.2.1 on 2025-06-03 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_course_includes_instructor_course_includes_insurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='certification_level',
            field=models.CharField(choices=[('NONE', 'NO'), ('BEGINNER', 'SCUBA'), ('OPEN_WATER', 'OWD.'), ('ADVANCED_OPEN_WATER', 'ADV.'), ('RESCUE_DIVER', 'RESC.'), ('DIVEMASTER', 'DM.'), ('INSTRUCTOR', 'INST.')], default='NONE', max_length=50),
        ),
    ]
