# Generated by Django 5.2.1 on 2025-06-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_customer_certification_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdiveactivity',
            name='needs_fins',
            field=models.BooleanField(default=False),
        ),
    ]
