# Generated by Django 5.2.1 on 2025-06-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customerdiveactivity_needs_fins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseenrollment',
            name='status',
            field=models.CharField(choices=[('ENROLLED', 'Inscritp'), ('IN_PROGRESS', 'En progrso'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado'), ('ON_HOLD', 'En espera')], default='ENROLLED', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='session_type',
            field=models.CharField(choices=[('THEORY', 'Sesión teórica'), ('POOL', 'Aguas Confinadas'), ('OPEN_WATER', 'Aguas Abiertas'), ('EXAM', 'Examen'), ('PRACTICAL', 'Habilidades')], default='OPEN_WATER', max_length=20),
        ),
        migrations.AlterField(
            model_name='coursesession',
            name='status',
            field=models.CharField(choices=[('NOT_SCHEDULED', 'Sin pogramar'), ('SCHEDULED', 'Programado'), ('IN_PROGRESS', 'En progrso'), ('COMPLETED', 'Completado'), ('CANCELLED', 'Cancelado'), ('RESCHEDULED', 'Reprogramado')], default='NOT_SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='staff',
            name='certification_level',
            field=models.CharField(choices=[('DIVEMASTER', 'Divemaster'), ('INSTRUCTOR', 'Instructor'), ('SENIOR_INSTRUCTOR', 'Senior Instructor'), ('MASTER_INSTRUCTOR', 'Master Instructor'), ('COURSE_DIRECTOR', 'Course Director'), ('SKIPPER', 'Marinero'), ('DRIVER', 'Patrón')], default='DIVEMASTER', max_length=50),
        ),
        migrations.AlterField(
            model_name='staff',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo'), ('ON_LEAVE', 'Ausente')], default='ACTIVE', max_length=20),
        ),
    ]
