# Generated by Django 5.2.1 on 2025-06-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_add_primary_instructor_to_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdiveactivity',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de llegar'), ('ON_BOARD', 'On Board'), ('BACK_ON_BOAT', 'Back on Boat'), ('DEPARTED', 'En curso'), ('FINISHED', 'Finalizado')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerdiveactivity',
            name='tank_size',
            field=models.CharField(choices=[('10L', '10L'), ('12L', '12L'), ('15L', '15L'), ('EAN12L', 'NITROX 12L'), ('EAN15L', 'NITROX 15L')], default='12L', max_length=10),
        ),
    ]
