# Generated by Django 5.2.1 on 2025-06-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_courseenrollment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='medical_questionnaire_answers',
            field=models.JSONField(blank=True, default=dict, help_text='Stores answers to medical questionnaire'),
        ),
        migrations.AddField(
            model_name='customer',
            name='swimming_ability',
            field=models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20),
        ),
    ]
