# Generated by Django 5.2.1 on 2025-06-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customer_medical_questionnaire_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='customer_signatures/'),
        ),
    ]
