# Generated by Django 5.2.2 on 2025-06-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_customer_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('ES', 'Spanish'), ('FR', 'French'), ('NL', 'Nederlands'), ('DE', 'Deutsch'), ('CAT', 'Catalan')], default='EN', max_length=10),
        ),
    ]
