# Generated by Django 5.2.2 on 2025-06-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_customer_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='certification_level',
            field=models.CharField(choices=[('NONE', 'NO'), ('BEGINNER', 'SCUBA'), ('OPEN_WATER', 'OWD.'), ('ADVANCED_OPEN_WATER', 'ADV.'), ('RESCUE_DIVER', 'RESC.'), ('DIVEMASTER', 'DM.'), ('INSTRUCTOR', 'INST.')], default='Ninguna', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='language',
            field=models.CharField(choices=[('CAT', 'Català'), ('ES', 'Español'), ('FR', 'Français'), ('EN', 'English'), ('NL', 'Nederlands'), ('DE', 'Deutsch')], default='EN', max_length=10),
        ),
    ]
